$(function(){
	//角色列表
	$("#role_tbo").datagrid({
		url:prefix+"//loadRolesAll",
		fit:true,
		fitColumns:true,
		striped:true,
		border:false,
		pagination:true,
		pageSize:10,
		pageList:[10,20,30],
		pageNumber:1,
		toolbar:"#role_tbar",
		columns:[[
			{
				field:"role_id",
				title:"用户编号",
				width:100,
			},
			{
				field:"role_name",
				title:"角色名称",
				width:100,
			},
			{
				field:"role_desc",
				title:"角色描述",
				width:200,
			},
			{
				field:"state",
				title:"状态",
				width:100,
				formatter:function(value){
					if(value=="0"){
						return "禁用";
					}else if(value=="1"){
						return "启用";
					}
				},
			}
		]],
	});
	//用户列表
	$("#user_tbo").datagrid({
		url:prefix+"/loadUsersAll",
		fit:true,
		fitColumns:true,
		striped:true,
		border:false,
		pagination:true,
		pageSize:10,
		pageList:[10,20,30],
		pageNumber:1,
		toolbar:"#user_tbar",
		columns:[[
			{
				field:"user_id",
				title:"用户编号",
				width:100,
			},
			{
				field:"user_name",
				title:"用户账号",
				width:100,
			},
			{
				field:"show_name",
				title:"用户名称",
				width:100,
			},
			{
				field:"e_mail",
				title:"邮箱",
				width:100,
			},
			{
				field:"phone",
				title:"电话",
				width:100,
			},
			{
				field:"state",
				title:"状态",
				width:100,
				formatter:function(value){
					if(value=="0"){
						return "禁用";
					}else if(value=="1"){
						return "启用";
					}
				},
			}
		]],
	});
	//菜单树
	$('#menu_ul').tree({
		url:prefix+"/loadTerr",
		lines:true,
		checkbox:true,
		onClick:function(node){
			
		},
		onLoadSuccess:function(node,data){
		  if (data) {
			  $('#menu_ul').tree('expandAll');
	      }
		}
	});
	//角色列表
	$("#menu_tbo").datagrid({
		url:prefix+"//loadRolesAll",
		fit:true,
		fitColumns:true,
		striped:true,
		border:false,
		pagination:true,
		pageSize:10,
		pageList:[10,20,30],
		pageNumber:1,
		columns:[[
			{
				field:"role_id",
				title:"用户编号",
				width:100,
			},
			{
				field:"role_name",
				title:"角色名称",
				width:100,
			},
			{
				field:"role_desc",
				title:"角色描述",
				width:200,
			},
			{
				field:"state",
				title:"状态",
				width:100,
				formatter:function(value){
					if(value=="0"){
						return "禁用";
					}else if(value=="1"){
						return "启用";
					}
				},
			}
		]],
	});
});